### PR TITLE
Add support for improved Tooltips

### PR DESCRIPTION
**Pull request by goldenxp**
image

### CODE REVIEW

**Comment by goldenxp** [comment]
Let me know if this is acceptable and I can add the rest of the hints in. It's a bit more time consuming than some regex changes :)

**Comment by VilleKrumlinde** [comment]
Hi,

Thanks for your efforts.

A hint per property is a nice idea. Although I did made an effort of making property names self-descriptive so I don't think they will all need hints.

I'm not a big fan of using resourcestrings.

I would just add a few hints directly like this where needed.

`  List.GetLast.Hint := 'Read only. The current number of frames per second.'
`  

Is there a reason you want to use resource strings? Maybe if you describe your main goals here then I can understand what you are trying to do.

**Comment by goldenxp** [comment]
I'm hoping with resource strings, localization will be easier to do. 
I agree a lot of the properties are self describing. Sometimes I think a short definition or tip could help.

**Comment by VilleKrumlinde** [comment]
Are there user requests for localization though? The current amount of ZGE users isn't exactly huge and most seems to speak English :)

And there are localizations solutions such as gnugettext that doesn't require resourcestrings.

**Comment by goldenxp** [comment]
That's fair. If you are still okay with tooltips hints, let me know and I can make a new PR.

**Comment by VilleKrumlinde** [comment]
> That's fair. If you are still okay with tooltips hints, let me know and I can make a new PR.

Sure, please make a new PR. Thanks.

**Pull request closed without merging**
