### PR TITLE
Create makeAndroid.bat

### PR DESCRIPTION
**Pull request by Txori**
A single script to build libraries for android 32 and 64.
FPC_PATH and NDK_PATH can be set.
DEBUG can be set to true to automatically add -g flag for logcating and stacktracing.

### CODE REVIEW

**Review by Txori — COMMENTED** [review]
I managed to build the android library using the current NDK 27b instead of the good ole 21e

**Comment by VilleKrumlinde** [comment]
Perhaps best to delete this PR and make a new one? I'm not sure how to only merge the first revision.

**Comment by Txori** [comment]
hahaha. I don't have rights to delete that PR... Delete it if you can, I'll make another one with the last bat file I made for all those build tests :)

**Comment by VilleKrumlinde** [comment]
Closing it and awaiting new PR 😊

**Pull request closed without merging**
